# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-15 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[(1, 'FUTURE RESERVATION'), (2, 'CHECK-IN'), (3, 'CHECK-OUT'), (4, 'CANCELLED')], default='FUTURE RESERVATION', max_length=255)),
            ],
        ),
    ]
